#!/bin/bash

# monit-enconf --- Bash completion function for monit_enconf/monit_disconf.

# Copyright (C) 2010 António P. P. Almeida <appa@perusio.net>

# Author: António P. P. Almeida <appa@perusio.net>

# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# Except as contained in this notice, the name(s) of the above copyright
# holders shall not be used in advertising or otherwise to promote the sale,
# use or other dealings in this Software without prior written authorization.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.


## Handling of both enabled and available confs.
_monit_confs() {
    # Get the available or enabled confs for monit.
    COMPREPLY=( $( compgen -W '$( command find /etc/monit/$1 -type f -printf "%P " 2>/dev/null \
               | sed 's/[.]conf$//' )' -- $cur  ) )
}

_monit_enconf()
{
       local cur

       COMPREPLY=()
       cur=${COMP_WORDS[COMP_CWORD]}

       _monit_confs confs-available
}

complete -F _monit_enconf monit_enconf

_monit_disconf()
{
       local cur

       COMPREPLY=()
       cur=${COMP_WORDS[COMP_CWORD]}

       _monit_confs confs-enabled
}

complete -F _monit_disconf monit_disconf
